apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - default: 'https://github.com/CSCI-GA-2820-SP26-003/shopcarts.git'
      description: The URL to the git repo
      name: GIT_REPO
      type: string
    - default: master
      description: The reference (branch or ref)
      name: GIT_REF
      type: string
    - description: The external OpenShift route URL for the deployed microservice
      name: BASE_URL
      type: string
    - default: shopcarts
      description: Name of app
      name: APP_NAME
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest'
      description: Name of the image
      name: IMAGE_NAME
      type: string
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: |
            oc apply -f k8s/deployment.yaml
            oc apply -f k8s/service.yaml
            oc apply -f k8s/ingress.yaml
            oc set image deployment/$(params.APP_NAME) $(params.APP_NAME)=$(params.IMAGE_NAME)
            oc rollout status deployment/$(params.APP_NAME) --timeout=300s
      runAfter:
        - buildah
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: manifest-dir
          workspace: pipeline-workspace
    - name: bdd-tests
      params:
        - name: base-url
          value: $(params.BASE_URL)
      runAfter:
        - deploy
      taskRef:
        kind: Task
        name: behave
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: pylint
      params:
        - name: image
          value: 'quay.io/rofrano/python:3.12-slim'
        - name: path
          value: service
        - name: args
          value: []
        - name: requirements-file
          value: requirements.txt
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: pylint
      workspaces:
        - name: source
          workspace: pipeline-workspace
    # Run pytest with coverage enforcement
    - name: pytest
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: pytest-env
      params:
        - name: pytest-args
          value:
            - "--cov=service"
            - "--cov-fail-under=95"
            - "--disable-warnings"
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: buildah
      params:
        - name: IMAGE_NAME
          value: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/shopcarts:latest'
      runAfter:
        - pylint
        - pytest
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-workspace
  workspaces:
    - name: pipeline-workspace
